apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: observability-platform
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
