apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability-staging

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patch-configmap.yaml
  - path: patch-backend-deployment.yaml
  - path: patch-frontend-deployment.yaml
  - path: patch-ingress.yaml

images:
  - name: ghcr.io/your-org/k8s-observability-backend
    newTag: staging
  - name: ghcr.io/your-org/k8s-observability-frontend
    newTag: staging
