apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    monitoring: platform
spec:
  namespaceSelector:
    matchNames:
      - observability-dev
      - observability-staging
      - observability-prod
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-servicemonitor
  namespace: monitoring
  labels:
    monitoring: platform
spec:
  namespaceSelector:
    matchNames:
      - observability-dev
      - observability-staging
      - observability-prod
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  endpoints:
    - port: http
      path: /healthz
      interval: 30s
      scrapeTimeout: 10s
