apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secrets.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | quote }}
